name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get CloudFront and API Gateway info
        id: tf_outputs
        working-directory: ./terraform
        run: |
          echo "api_url=$(terraform output -raw api_url)" >> $GITHUB_ENV
          echo "cloudfront_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

      - name: Inject API URL into script.js
        run: |
          sed -i "s|{{API_URL}}|$API_URL|g" frontend/script.js

      - name: Upload frontend to S3
        run: aws s3 sync frontend/ s3://${{ secrets.AWS_S3_BUCKET }} --delete

      - name: Reset script.js to template
        run: |
          sed -i "s|$API_URL|{{API_URL}}|g" frontend/script.js

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$cloudfront_id" \
            --paths "/*"
