name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get API Gateway and CloudFront IDs dynamically
        id: ids
        shell: bash
        run: |
          API_ID=$(aws apigateway get-rest-apis \
            --query "items[?name=='CloudResumeCounterAPI'].id" \
            --output text)

          CLOUDFRONT_ID=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[?Aliases.Items[?@=='${{ secrets.ROOT_DOMAIN }}']].Id" \
            --output text)

          if [[ -z "$API_ID" || -z "$CLOUDFRONT_ID" ]]; then
            echo "Missing API ID or CloudFront ID. Exiting."
            exit 1
          fi

          API_URL="https://${API_ID}.execute-api.${{ secrets.AWS_REGION }}.amazonaws.com/prod/counter"
          echo "API_URL=$API_URL" >> "$GITHUB_ENV"
          echo "CLOUDFRONT_ID=$CLOUDFRONT_ID" >> "$GITHUB_ENV"

      - name: Inject API URL into assets/script.js
        shell: bash
        run: |
          sed -i "s|{{API_URL}}|$API_URL|g" frontend/assets/script.js

      - name: Upload frontend to S3
        shell: bash
        run: |
          aws s3 sync frontend/ "s3://${{ secrets.BUCKET_NAME }}/" \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "node_modules/*"

      - name: Reset script.js placeholder (local workspace)
        if: always()
        shell: bash
        run: |
          sed -i "s|$API_URL|{{API_URL}}|g" frontend/assets/script.js

      - name: Invalidate CloudFront cache
        shell: bash
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CLOUDFRONT_ID" \
            --paths "/*"
