name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure Terraform backend dynamically
        working-directory: ./terraform
        run: |
          sed -i 's|__BACKEND_BUCKET__|${{ secrets.TF_STATE_BUCKET }}|' backend.tf
          sed -i 's|__BACKEND_KEY__|${{ secrets.TF_STATE_KEY }}|' backend.tf
          sed -i 's|__BACKEND_REGION__|${{ secrets.AWS_REGION }}|' backend.tf

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply (auto-approve to ensure state)
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Get Terraform outputs safely
        working-directory: ./terraform
        run: |
          API_URL=$(terraform output -raw api_url)
          CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id)
          echo "API_URL=$API_URL" >> $GITHUB_ENV
          echo "CLOUDFRONT_ID=$CLOUDFRONT_ID" >> $GITHUB_ENV

      - name: Inject API URL into script.js
        run: |
          sed -i "s|{{API_URL}}|$API_URL|g" frontend/script.js

      - name: Upload frontend to S3
        run: aws s3 sync frontend/ s3://${{ secrets.AWS_S3_BUCKET }} --delete

      - name: Reset script.js to template
        run: |
          sed -i "s|$API_URL|{{API_URL}}|g" frontend/script.js

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CLOUDFRONT_ID" \
            --paths "/*"
